[program:radio-queue-worker]
command=php /var/www/backend/bin/queue-worker.php
directory=/var/www/backend
autostart=true
autorestart=true
startretries=3
user=www-data
numprocs=1
stdout_logfile=/var/log/radio-queue-worker.log
stderr_logfile=/var/log/radio-queue-worker.err.log
stopwaitsecs=10
stopsignal=TERM
environment=APP_ENV="prod",TZ="Europe/Istanbul"
